### ISSUE TITLE
I/O errors with neo protocol when app reconnects to DHT nodes

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/dhtproto#109] opened 2018-01-31 12:09 UTC
This problem was observed with a test application interacting with 2 test neo DHT nodes, during a `dht.neo.getAll` request.  App logging reported the following I/O errors (seems to be one per DHT node):

```
Error [dhtproto.client.request.internal.GetHashRange] - I/O error: Expected non-zero errno after failure (connection hung up on read) @ ./submodules/swarm/src/swarm/neo/protocol/socket/MessageReceiver.d:558
Error [dhtproto.client.request.internal.GetHashRange] - I/O error: Expected non-zero errno after failure (connection hung up on read) @ ./submodules/swarm/src/swarm/neo/protocol/socket/MessageReceiver.d:558
```

A different error that shows up sometimes (in addition to the `GetHashRange` errors) is:

```
Error [dhtproto.client.request.internal.GetHashRange] - I/O error: Connection reset by peer (write error) @ ./submodules/swarm/src/swarm/neo/protocol/socket/MessageSender.d:399
```

Steps to reproduce:

* start neo DHT node(s) and copy data to channels

* start application that reads these channels, let it read

* kill application and restart it

* repeat until the error starts appearing

Restarting the DHT nodes appears to fix things (apparently without requiring the app itself to restart).  Restarting only _one_ of the two DHT nodes results in only one of the `non-zero errno` errors occurring at a time (rather than two at a time); restarting the second DHT node then stops the errors entirely.

**Comment by gavin-norman-sociomantic** [comment] 2018-05-03 10:10
I've tried to reproduce this as follows:
1. Set up a local DHT with 2 nodes.
2. Create a channel with 500K records.
3. Start a client that does a GetAll on the channel.
4. SIGINT the client before the request finishes. Restart it. Repeat.

I can't reproduce any errors with this setup.

**Comment by joseph-wakeling-sociomantic** [comment] 2018-05-03 10:23
I'll let you know if it starts showing up again in any future tests.  Is there a possibility this was a lower-level issue (say in swarm.neo) that may have been fixed on the basis of {dmq,dls}.neo experience ... ?

For the record, the channel(s) concerned were smaller (probably thousands or tens of thousands of records), although I can't imagine it would make any difference.

**Comment by gavin-norman-sociomantic** [comment] 2018-05-03 10:26
Yeah, it's possible it was a bug in swarm that's now been fixed. I'll remove this from neo-alpha-5.

**Comment by gavin-norman-sociomantic** [comment] 2018-06-11 14:27
I'll close this. We can repoen (or create new issues) if it pops up again when we start testing dhtproto neo-alpha-5.

**Closed as completed by gavin-norman-sociomantic** 2018-06-11 14:27 UTC
